/-
RFD 2152 stage 2 (planned): RISC-V assembly emit per FBD block.

Stage 1 defines the syscall constants that match godot-sandbox's
`gdscript.elf` ABI so the emitter's later body can reference them
without ABI drift. Emit bodies land under stage 2.

SPDX-License-Identifier: MIT OR Apache-2.0
-/
import TaskweftFbdCompiler

namespace TaskweftFbdCompiler.Riscv
open TaskweftFbdCompiler

/-- The godot-sandbox syscall numbers our .elf targets. Pinned here
    against the header the addon reads from; a drift shows up as an
    ELF the host refuses. Stage-5 follow-on: adopt the addon's own
    header verbatim rather than restating it. -/
def SYSCALL_PRINT             : Nat := 1
def SYSCALL_GET_VARIABLE      : Nat := 10
def SYSCALL_SET_VARIABLE      : Nat := 11
def SYSCALL_REGISTER_CALLABLE : Nat := 20
def SYSCALL_CALL_CALLABLE     : Nat := 21

/-- Emit RISC-V assembly text for one POU. Stage 2 body — for now,
    returns a placeholder header + entry stub. -/
def emitAsm (name : String) : String :=
  s!"# RISC-V assembly for POU {name}\n" ++
  s!"# Generated by TaskweftFbdCompiler.Riscv (RFD 2152 stage 1 stub)\n" ++
  s!".section .text.on_tick,\"ax\",@progbits\n" ++
  s!".globl on_tick\n" ++
  s!"on_tick:\n" ++
  s!"  # ecall #{SYSCALL_PRINT} 'FBD scan (stub)'\n" ++
  s!"  ret\n"

end TaskweftFbdCompiler.Riscv
